### ISSUE TITLE
Variation on SFS tag order

### ISSUE THREAD

**Issue by gehara** [isaacovercast/PTA#19]
There is variation on SFS tag order among replicates when using length = 100000 and num_replicates = 1. Row names of msfs_list[1].df won't necessarily match with msfs_list[2].df.

**Comment by isaacovercast** [comment]
Hm, that would be a problem. Let me look at it.

**Comment by isaacovercast** [comment]
Ah, yes, this is true. It's because if a config (an sfs bin) is not present in the data then it isn't included in the sfs. So if there is a sfs bin where there are no snps at that frequency in any of the samples, then it's not included in the msfs. This is okay, though, because when they are joined together and written to the SIMOUT file the are concatenated by index value, so the configs will always line up in the output, and empty configs will be filled with 0.

**Comment by isaacovercast** [comment]
Are you working with mSFS directly rather than using the SIMOUT file? This is not something I had anticipated. if you want to do that we will have to think about how to solve this problem.

**Comment by gehara** [comment]
This is what I'm doing. OK, now I understand why I was not getting good results.
